### ISSUE TITLE
How exactly does draw work with it's target?

### ISSUE THREAD

**Issue by ZweiEuro** [liballeg/allegro5#1141]
I have been trying for days to get a multithreaded rendering system to work, I've looked at everything I could find and the docs as well.
I have avery simple setup:
2 threads which draw onto 2 respective bitmaps and one of those threads occasionally writes to the display back buffer, but for some reason 
`  al_draw_textf(get_default_font(), al_color_name("black"), 1, 1, ALLEGRO_ALIGN_LEFT, "Drawn threads: %d ",times_drawn_);`
straight up fails and I have nothing to go on than a simple "SIGSEGV" Knowing there is somewhere a segfault in this lib.
Sadly locally the whole thing is hidden in assembly so it's impossible to reverse engineer even going by the function names, searching for them in the src code still doesn't conclude to any error.

This also Completely crashes my (wayland) system but I have gotten it to work before.
It works fine if there is only 1 thread doing the work, functional but not scalable or realistic.

If anyone has had similar problems please tell me,
I feel like I am reading the wiki and ref for the upteenth time.

All in all the call looks like this:
![1591196409_grim](https://user-images.githubusercontent.com/18036573/83652878-6890aa00-a5bb-11ea-8cb2-d112b9f6b6f3.png)

the position of the crash seems to not be very consistent but in this case it was [here](https://github.com/liballeg/allegro5/blob/9b36d6acbd32bfa2a34d8205b752d00b0446be91/src/opengl/ogl_lock.c#L416).
Sadly at this point it's not really possible to track what parameter here made what mistake since there are about 10 layers in between.

How do you even debug this ?

**Comment by ZweiEuro** [comment]
If yout want to try this out and compile it yourself:
https://github.com/ZweiEuro/game
I really just fear the possibility of some kind of memleak

**Comment by beoran** [comment]
This is a design that cannot work, at least not on most operating systems
and with OpenGL or DirectX 9. In these systems all drawing must be done on
the main thread, or at least on the thread that opened the display.

The workaround is to do all drawing on the main thread and handle ai,
collisions, maps, etc in other threads if necessary. A pure single threaded
design will also work.

Op wo 3 jun. 2020 17:02 schreef ZweiEuro <notifications@github.com>:

**Comment by ZweiEuro** [comment]
I am not drawing to the display from any other thread than 1, the one who created the display,
in my case my SystemThread object.
RenderThread draws on it's Bitmap, Compositor takes that bitmap and draws it onto it's internal and then draws it's internal out to the display.
Yes this is needlessly complex but the ultimate goal would be to make the compositor add up many Threads beneith it and then write those all into its internal and then that one to the display. 
I only make one call to the display

**Comment by ZweiEuro** [comment]
Or do you mean I can can only really draw from the main thread and never from the al_create_ 'ed threads ?

**Comment by ZweiEuro** [comment]
Or Rather @beoran can I call
draw_text or any other draw command onto bitmaps in threads that don't have any display?
Why wouldn't that work because it seems that's what I am experiencing here

**Comment by elias-pschernig** [comment]
OpenGL has an "OpenGL context" which is tied to the current thread. You cannot call any OpenGL functions without that context. So in general you should just draw from the main thread - you can still send draw commands to it from other threads (for example using a queue).

There is some ways to work around that - when you call [al_set_target_bitmap()](https://liballeg.org/a5docs/trunk/graphics.html#al_set_target_bitmap) it will check which thread you are calling it from and switch the display's OpenGL context to that thread if it is not the current one. So after that you can draw from this new thread (but drawing from the previous thread will crash). Which means you need to now make sure that when you call al_set_target_bitmap() on one thread no other thread does any drawing before you are done. Once you are done you can stop drawing and then another thread can call al_set_target_bitmap again, and so on.

This could be done by using thread synchronization (e.g. al_lock_mutex or al_wait_cond or al_wait_event) - but it will get very complex and performance will be worse than using a single thread for drawing since you still can only have one thread draw at a time. I don't think anyone ever attempted to do this.

Other ways to use multiple threads are using multiple windows like done in the [ex_threads](https://github.com/liballeg/allegro5/blob/master/examples/ex_threads.c) sample or drawing into memory bitmaps like done in [ex_threads2](https://github.com/liballeg/allegro5/blob/master/examples/ex_threads2.c) or [ex_loading_thread](https://github.com/liballeg/allegro5/blob/master/examples/ex_loading_thread.c). Note that you can only access memory bitmaps in the latter case, which includes fonts - checking the width of text using a display font will crash as that still would have to access the underlying OpenGL texture.

**Comment by ZweiEuro** [comment]
How do i know which fkt are opengl and which aren't?

What i am trying to do is actually just draw to bitmaps from my threads and the one who created the display will add them all up, just like in ex_thread2. 
It still crashes though. Am i not allowed to use any draw or text functions on memory bitmaps who don't have a display?

**Comment by ZweiEuro** [comment]
It's just opengl, not an allegro issue
