### ISSUE TITLE
segfault when trying to draw ribbons with more than 128 points

### ISSUE THREAD

**Issue by bart9h** [liballeg/allegro5#1157]
`ALLEGRO_VERTEX_CACHE_SIZE` is fixed, and small.

It would be nice to be able to draw arbitrarily long ribbons, but I could split them on my side.
Anyway, it should not segfault on Allegro side.

The simplest solution is to include a simple check at the beginning of `al_draw_ribbon()`:

    if (num_segments*2 > ALLEGRO_VERTEX_CACHE_SIZE) {
        fprintf(stderr,
            "Allegro is refusing to draw a ribbon with more than %d points.\n",
            ALLEGRO_VERTEX_CACHE_SIZE/2);
        return;
    }

**Comment by pedro-w** [comment]
It's good that this is fixed, but would it be possible to automatically split the segments into batches of suitable size and draw, instead of just failing as it does now? Or would there inevitably be artifacts where the splits happen?
Currently `al_draw_ribbon` calls `al_calculate_ribbon` and then `al_draw_prim` to draw as a line strip or triangle strip. It should not be too hard to iterate through the input vertices, calling calculate and draw on batches of `ALLEGRO_VERTEX_CACHE_SIZE` or less. 
What do you think?

**Comment by pedro-w** [comment]
Have a look at https://github.com/pedro-w/allegro5/tree/long-strip - seems to work, though I didn't test thoroughly. 
Adding an example for `al_draw_ribbon` into ex_prim might be worth doing anyway (see 4f694ce09e390de244728cfded5ea884279aca8d).
