### ISSUE TITLE
undefined reference to __cxa errors ( STATIC LINK ) Allegro 5.2.8.0

### ISSUE THREAD

**Issue by CraftingInC** [liballeg/allegro5#1405]
Greetings.
I am using latest repo :   
```
allegro-x86_64-w64-mingw32-gcc-12.1.0-posix-seh-static-5.2.8.0.zip 
```
I have MinGWx64 11.2 ( using GCC ) and I have my project setup in codeblocks. Windows 10. I want to use OpenGL, NOT directx.

I use this stable compiled windows GCC ( MinGWx64 ) version from here :  
```
https://nuwen.net/mingw.html
```
Side note : It's the most stable GCC version I have used. And I have been using it for years now.

I am currently referencing these libraries : 
```
-lallegro_monolith-static
-lgdi32
-lopengl32
-lwinmm
-lShlwapi
-lOle32
```

Referencing those libraries have solved all errors except the ones with the __cxa in them.
```
undefined reference to __cxa_guard_acquire
undefined reference to __cxa_guard_release
undefined reference to __cxa_guard_abort
undefined reference to __gxx_personality_seh0
```
I code in C, not C++.

Any ideas ?

**EDIT 1 :** For those who might suggest it, -fno-threadsafe-statics made no difference. Those undefines are still there.

**EDIT 2 :** For completness, I also tried this older version 
```
allegro-x86_64-w64-mingw32-gcc-10.2.0-posix-seh-static-5.2.7.0.zip 
```
It has the same exact undefine errors.

**EDIT 3 :** I have submitted this issue to the dev who compiled that version of MinGWx64 ( GCC ) that I use. I am hoping one dev or the other could help shed some light on this.

**EDIT 4 :** Examingin further and it looks like these undefines are coming from this file.
```
C:\dev\allegro_winpkg\universal\allegro\src\win\d3d_display_formats.cpp
```
Which by the way, that path to that file does NOT exist on my machine. It's apparently being called from inside the 
allegro_monolith-static  library.
I tried not including that and just using the others, 
```
allegro-static
allegro_font-static
```
but I still get same UNDEFINED errors.

Keep in mind, this is all related to d3d ( DirectX library ). No matter what I tried to include for DirectX (even though I'm not using it), the undefined didn't go away.

**EDIT 5 :** I did try to include the directX into it 
```
-ld3d11   and I tried -ld3d12
```
but it made no difference.

Forum posts around the net are claiming that Allegro is going toward C++ only. I hope this is not true.

**Comment by SiegeLord** [comment]
You need to link in the C++ runtime libraries, done most easily by linking with g++.

On Windows, Allegro interacts with some Windows API via C++. It might be possible to compile Allegro without those bits (they are primarily DirectX), but as you're using the pre-compiled binaries, that's not an option here.

**Comment by CraftingInC** [comment]
I'm using GCC because I don't want to use C++. I want to stick with C. Allegro is pure C, except this one problem. And I didn't want to have to recompile the Allegro library. Which is the whole point of my using those pre-compiled binaries. Otherwise, why bother ?

With that said however, I did try linking in the C++ libs, but it didn't change anything. I still get those same Undefines.

**Comment by beoran** [comment]
Allegro in itself has a C interface, but on Windows, certain functionality is implemented in C++, so it is required to link the necessary C++ libraries. While technically we could implement the same functionality in C, it turned out to be difficult to do so.

**Comment by CraftingInC** [comment]
> Allegro in itself has a C interface, but on Windows, certain functionality is implemented in C++, so it is required to link the necessary C++ libraries. While technically we could implement the same functionality in C, it turned out to be difficult to do so.

Based on your reply, this would mean I can't use C for this binary. If that's the case, I guess I'll close this ISSUE and move on to a different library, since I can't code in C with Allegro.

Which means, everyone who said this is a C++ library has been correct. Which means all my C coders from my YT channel can't use it either. I will have to inform them of this. Thank you for clarifying. It's a shame that it's posted as a C library for use with C, but it's really not.
Cheers

**Comment by beoran** [comment]
If you feel allegro should be written in pure C only, then contributions to that effect would be welcome. 

But, you will find that many other multimedia libraries like SDL or GLFW also use C++ or objective C  under the hood, because implementing multimedia libraries with pure C only is difficult on Windows or OS-X, since these systems use C++ or Objective-C for their UI libraries.

With Allegro or those other libraries you can still write your own software in pure C. The only downside of this is that you have to link C++ or Objective-C libraries on certain platforms. On Linux, for example, Allegro is implemented in pure Cas well.

**Comment by SiegeLord** [comment]
> I can't code in C with Allegro.

If your definition of 'code in C' means that there isn't a shred of C++ anywhere in your binary, then you're right in principle (as long as Win32 code doesn't have C++ in it, which I'm not sure about). I don't think that's a reasonable definition, however. You can write your program in pure C, and then link the necessary libraries as required by the dependencies. There's two options:

1. Static linking. I don't know why `-lstdc++` didn't work for you. I just tested it, and it worked fine. Here's the example command I used:

```
gcc main.c -o bin/main.exe -Llib -Iinclude -lallegro_monolith-static -ldumb -lFLAC -lfreetype -ljpeg -lopusfile -lopus -lphysfs -lpng16 -ltheoradec -lvorbis -lvorbisfile -logg -lwebp -lzlib -ldsound -lopengl32 -luser32 -lgdi32 -lcomdlg32 -lole32 -lwinmm -lkernel32 -lpsapi -lshlwapi -lstdc++
```

You can also link-in the C++ runtime statically, if you don't want to distribute its dlls:

```
gcc main.c -o bin/main.exe -Llib -Iinclude -static-libgcc -static-libstdc++ -static -lpthread -lallegro_monolith-static -ldumb -lFLAC -lfreetype -ljpeg -lopusfile -lopus -lphysfs -lpng16 -ltheoradec -lvorbis -lvorbisfile -logg -lwebp -lzlib -ldsound -lopengl32 -luser32 -lgdi32 -lcomdlg32 -lole32 -lwinmm -lkernel32 -lpsapi -lshlwapi -lstdc++
```

2. Dynamic linking. The pre-compiled binaries with the `-static` suffix are particularly good for this, as they statically link-in the C++ runtime inside of them.

**Comment by pedro-w** [comment]
Also @CraftingInC I'd be interested to know who are the people / forums who are saying Allegro is a C++ library? 
Because I think they are incorrect with this. Actually, as far as I can see there's less C++ in Allegro than SDL2 and certainly less than SFML.
Siegelord and the others who have replied in this issue are the actual Allegro developers so I believe they are more likely to give you a definitive answer than 'forum posts around the net'

**Comment by CraftingInC** [comment]
I did some digging, because I wanted to make sure I was correct before I brought this up. BUT from all my years of coding in C, I have never once used ANY Standard Template Libraries (STL) for C++, while coding in C. You CAN use Standard C library in C++, but NOT the other way around. I have yet to see ANY evidence of this happening for C. Which is why I have been so confused by all of you who keep suggesting that I use the Standard C++ libraries with my C projects. I didn't want to say anything until I looked this up. And so far, nothing proves that what you all are suggesting is even removely possible.

Example, in C++ you can use #include <vector> which allows you to use Vectors in your C++ projects. C does not have this ability. If you want Vectors in C, you have to code it. The Vector Template is in the standard C++ library. So I repeat, you CAN NOT use this in C at all. No matter even if you try to include the Standard C++.   C++ is an Object Oriented Language, C is not. And it can't use C++ Standard Template Library because of how the C++ library is designed.

My guess is, you are all using a C++ / g++ compiler of some sort and thinking it's a C compiler. Because again, you CAN compile C code in C++, not the other way around.

With that said, if you make a library, you CAN setup a C like interface, so that you can use C as your language, which allows C programmers the ability to use the library functions. I was under the impression you all knew this which is why I was so confused by your suggestions.

**Comment by beoran** [comment]
OK, in stead of debating about whether allegro is C or not, let's focus on the problem at hand. 

First of all the question is where the references to __cxa_guard_acquire, etc are coming from. I would check all libraries you are using , including the Allegro library with the ldd command line utility. If it is the case that the allegro library has this reference, then this might be caused due to relatively recent changes to the mingw64 C++ compiler used to compile certain Windows Allegro code. 
 
If that is the case then we might have to add a -fno-threadsafe-statics somewhere in the compilation of said c++ code to avoid emitting these references from being emitted.

Please understand that Allegro is a very old library, and we are severely understaffed. Criticizing us for something the g++ developers decided to do is rather pointless. As I said before, your help in fixing this would be most appreciated.

**Comment by CraftingInC** [comment]
There is no debate or criticizing attempt happening here.

With that said, all 4 of those errors stem from the d3d_display_formats.cpp file. I looked at it, but I'm not a C++ programmer. So I can't help any further.

**Comment by CraftingInC** [comment]
There is no debate or criticizing attempt happening here.

With that said, all 4 of those errors stem from the d3d_display_formats.cpp file.

EDIT : The libraries I have used when I tried to compile, I listed above. They all were needed in order to remove all of the __imp undefines.

EDIT 2 : I did install DirectX 9 SDK ( June 2010  version ) just to verify if that was what was missing. The reason I chose it is because the d3d_display_formats.cpp files and all the other directx cpp files referenced that old DirectX version. BUT it made no difference. The __cxa undefines are still there.

**Comment by CraftingInC** [comment]
There is no debate or criticizing attempt happening here.

With that said, all 4 of those errors stem from the d3d_display_formats.cpp file.

The libraries I have used when I tried to compile, I listed above. They all were needed in order to remove all of the __imp undefines.

I did install DirectX 9 SDK ( June 2010  version ) just to verify if that was what was missing. The reason I chose it is because the d3d_display_formats.cpp files and all the other directx cpp files referenced that old DirectX version. BUT it made no difference. The __cxa undefines are still there.

**Comment by CraftingInC** [comment]
There is no debate or criticizing attempt happening here on my end. It was about understanding the suggestions, and seeing if there were alternative reasons to those suggestions that might have been overlooked.

With that said, all 4 of those errors stem from the d3d_display_formats.cpp file.

The libraries I have used when I tried to compile, I listed above. They all were needed in order to remove all of the __imp undefines.

I did install DirectX 9 SDK ( June 2010  version ) just to verify if that was what was missing. The reason I chose it is because the d3d_display_formats.cpp files and all the other directx cpp files referenced that old DirectX version. BUT it made no difference. The __cxa undefines are still there.

**Comment by beoran** [comment]
These symbols are likely to be generated by the c++ compiler, as it is compiling this file, so changing the DirectX library is unlikely to have any effects. It would be more likely to add that -fno-threadsafe-statics flag to the c++ flags in the CMake file of allegro and recompiling it.

**Comment by SiegeLord** [comment]
> SeigLord, did you try my version of MinGWx64 ( GCC ) in my link above ?

Yes, I did. It works fine, with `-lstdc++` using the commands I provided in my last post.

**Comment by pedro-w** [comment]
> Static linking. I don't know why -lstdc++ didn't work for you. I just tested it, and it worked fine.

> SeigLord, did you try my version of MinGWx64 ( GCC ) in my link above ? Try it with that, you will see there is no command line switch of -stdc++. 

You're missing an 'l' here: `-lstdc++` not `-stdc++`

I think there's a mix up between compiling and linking - gcc (and g++) are front-end driver programs and they can compile and/or link depending on the input given to them

* When static linking you need to satisfy dependencies transitively (i.e. dependencies of your dependencies and so on)
* Allegro uses C++ internally (For DirectX, using the C interface is really painful)
* Therefore you need to link to C++ standard library

But this doesn't affect the use of gcc to compile C files.

You can try `-lstdc++`, or alternatively linking with g++ (compile with gcc and link with g++) because that includes the C++ libraries automatically. Another option may be to use the dynamic version of Allegro as that does the right thing behind the scenes I believe.

On the Allegro side we could investigate building with `-fno-threadsafe-statics` but those `__cxa_XXX` functions are there for a reason so I'm not sure without research what the implications would be.

**Comment by pedro-w** [comment]
> EDIT 2 :
> "The __cxa thing is related to C++'s "unwind" stack (for automatic calling of destructors for function scoped variables, particularly when processing an exception)."
> 
> SOURCE HERE :
> https://stackoverflow.com/questions/74578472/undefined-refrences-to-imp-and-cxa-when-linking-libraw
> 
> So that verified it. This is set for C++. Meaning that the devs of Allegro overlooked this for C compilers.

Irrelevant for this discussion but I think it's actually related to C++ static initializers, see 
https://manishearth.github.io/blog/2015/06/26/adventures-in-systems-programming-c-plus-plus-local-statics/

**Comment by CraftingInC** [comment]
> You're missing an 'l' here: `-lstdc++` not `-stdc++`
> 
> I think there's a mix up between compiling and linking - gcc (and g++) are front-end driver programs and they can compile and/or link depending on the input given to them
> 
>     * When static linking you need to satisfy dependencies transitively (i.e. dependencies of your dependencies and so on)
> 
>     * Allegro uses C++ internally (For DirectX, using the C interface is really painful)
> 
>     * Therefore you need to link to C++ standard library
> 
> 
> But this doesn't affect the use of gcc to compile C files.
> 
> You can try `-lstdc++`, or alternatively linking with g++ (compile with gcc and link with g++) because that includes the C++ libraries automatically. Another option may be to use the dynamic version of Allegro as that does the right thing behind the scenes I believe.


That was a typo on my part when I posted the reply. 


> > EDIT 2 :
> > "The __cxa thing is related to C++'s "unwind" stack (for automatic calling of destructors for function scoped variables, particularly when processing an exception)."
> > SOURCE HERE :
> > https://stackoverflow.com/questions/74578472/undefined-refrences-to-imp-and-cxa-when-linking-libraw
> > So that verified it. This is set for C++. Meaning that the devs of Allegro overlooked this for C compilers.
> 
> Irrelevant for this discussion but I think it's actually related to C++ static initializers, see https://manishearth.github.io/blog/2015/06/26/adventures-in-systems-programming-c-plus-plus-local-statics/

And this is why I'm going to leave this C++ stuff to you fellas. You seem to know what you are doing. Cheers.

**Comment by CraftingInC** [comment]
> You're missing an 'l' here: `-lstdc++` not `-stdc++`
> You can try `-lstdc++`, or alternatively linking with g++ (compile with gcc and link with g++) because that includes the C++ libraries automatically. Another option may be to use the dynamic version of Allegro as that does the right thing behind the scenes I believe.


That was a typo on my part when I posted the reply. 


> > EDIT 2 :
> > "The __cxa thing is related to C++'s "unwind" stack (for automatic calling of destructors for function scoped variables, particularly when processing an exception)."
> > SOURCE HERE :
> > https://stackoverflow.com/questions/74578472/undefined-refrences-to-imp-and-cxa-when-linking-libraw
> > So that verified it. This is set for C++. Meaning that the devs of Allegro overlooked this for C compilers.
> 
> Irrelevant for this discussion but I think it's actually related to C++ static initializers, see https://manishearth.github.io/blog/2015/06/26/adventures-in-systems-programming-c-plus-plus-local-statics/

And this is why I'm going to leave this C++ stuff to you fellas. You seem to know what you are doing. Cheers.

**Comment by CraftingInC** [comment]
Just so that there is no misunderstanding, I posted a picture of the undefines in question. At least you can see there are no other errors / warnings. It's just those  __cxa   and    __gxx undefines that are causing the issue.

https://imgur.com/a/rdzgoin

**Comment by beoran** [comment]
Yes, we can see that you have undefined references, but your full ld command with all options would be more useful.

**Comment by CraftingInC** [comment]
> Yes, we can see that you have undefined references, but your full ld command with all options would be more useful.

DEBUG
gcc.exe -Wall -std=c17 -m64 -g -Ilibs\allegro\include -c main.c -o obj\Debug\main.o
gcc.exe -Llibs\allegro\lib -o bin\Debug\AllegroTest.exe obj\Debug\main.o  -static -m64 -lallegro_monolith-static -lgdi32 -lopengl32 -lwinmm -lShlwapi -lOle32


RELEASE
gcc.exe -Wall -std=c17 -m64 -O2 -Ilibs\allegro\include -c main.c -o obj\Release\main.o
gcc.exe -Llibs\allegro\lib -o bin\Release\AllegroTest.exe obj\Release\main.o  -static -m64 -lallegro_monolith-static -lgdi32 -lopengl32 -lwinmm -lShlwapi -lOle32 -s

Hope this helps.

**Comment by pedro-w** [comment]
This is weird. On the very same version of allegro and with mingw from the site you mention above I can use the line

    gcc -o me.exe me.c -lallegro_monolith-static -lgdi32 -lopengl32 -lwinmm -lShlwapi -lOle32 -lstdc++

to give me a working `me.exe` without link errors. (Note I used `-lstdc++` which you've already said didn't make a difference/wasn't a valid option for you). I also tried `-std=c17 -m64 -static` since you've specified them, and it still worked.

Alternatively this also worked (dynamic linking)

     gcc -o me.exe me.c -lallegro_monolith

What else can we test?

(I'm using Windows 11 by the way)

**Comment by CraftingInC** [comment]
Yea, I don't get it either.

Also, as I mentioned in my original post, I'm on windows 10. But I can't see how that would be the difference. Unless I'm missing something here.

And as I mentioned earlier, the DirectX portion of Allegro is using DirectX 9 anyhow. So it shouldn't make a difference whether on Windows 10 or 11. But who knows. Maybe it does matter ?

**Comment by CraftingInC** [comment]
Ok I am making this a separate post so as to not confuse the above post.

To rule out codeblocks, I compiled without codeblocks. I compiled at command prompt.

https://imgur.com/a/ije4gAj

Picture showing same exact undefines. So this is not codeblocks related. We can rule that out.

**Comment by pedro-w** [comment]
Alright - can you now try exactly that command line from your image, but with `-lstdc++` at the _end_ of it?

On some compilers/platforms the order of link libraries on the command line matters, I can't remember if that would be the case here (someone else can chip in!)

> And the reason I am showing pictures, is because I didn't want you all thinking I was trolling you.

I'm old enough to remember when clicking on an unexpected image link would risk leading you to Rick Astley or worse. Text is fine, we believe you! 

Also, where you had
```
RELEASE
gcc.exe -Wall -std=c17 -m64 -lstdc++ -O2 -Ilibs\allegro\include -c main.c -o obj\Release\main.o
gcc.exe -Llibs\allegro\lib -o bin\Release\AllegroTest.exe obj\Release\main.o  -static -m64 -lallegro_monolith-static -lgdi32 -lopengl32 -lwinmm -lShlwapi -lOle32 -s
```
the `-lstdc++` needs to go in the second command line - first line compiles, second line links.

Finally I think  `-fno-threadsafe-statics` is never going to help you here because those naughty references to `__cxa_XXX` are baked  into the allegro_monolith-static.lib already, it's too late to remove them. It might help if you were compiling Allegro and it's probably something the developers should investigate.

**Comment by CraftingInC** [comment]
Here is a picture with it.

https://imgur.com/a/E8YahVl

**Comment by CraftingInC** [comment]
Here is a picture with it in both first and second lines.

https://imgur.com/a/EACnkQK

**Comment by pedro-w** [comment]
Getting close now I can feel it in my bones...

Can you try with `-lstdc++` at the _end_ of the linker command line?

See https://stackoverflow.com/questions/11893996/why-does-the-order-of-l-option-in-gcc-matter for an explanation. I think this still holds true.

**Comment by CraftingInC** [comment]
> Getting close now I can feel it in my bones...
> 
> Can you try with `-lstdc++` at the _end_ of the linker command line?
> 
> See https://stackoverflow.com/questions/11893996/why-does-the-order-of-l-option-in-gcc-matter for an explanation. I think this still holds true.

You sir are amazing. That actually worked on the command line. I'll make sure to note this in my video. I learned something new.

I will have to figure out how to specify the order in codeblocks

Thank you, again, you are amazing.

**Comment by CraftingInC** [comment]
I just spoke to a colleague and he didn't think this was possible either with that -stdc++. We were shocked to see that work. So my hats off to you. I am humbled beyond belief.

**Comment by beoran** [comment]
To explain a bit: What that -lstdc++ does when linking is link in the C++ standard library and resolve the references to these cxa_... symbols. The for GCC linker order does matter. In this case -lstdc needs to come after the Allegro library because the Allegro library referenties those symbols and the standard c++ library contains the implementation of those references.

**Comment by pedro-w** [comment]
Teamwork! Thanks all. I look forward to seeing what you make with Allegro, @CraftingInC ! By the way I recommend joining the Discord or allegro.cc as it's probably a quicker way to get answers to your questions.
