### ISSUE TITLE
Pausing mixer causes 100% CPU usage on Linux

### ISSUE THREAD

**Issue by WickedSmoke** [liballeg/allegro5#1445]
Using al_set_mixer_playing(mixer, 0) causes the CPU usage to jump to 100% on Fedora 37.  When audio is playing CPU usage is only 2%.

The following audio chain is used:  voice <- mixerA <- (mixerB & stream).

MixerA is the one being paused.  It has not been tried on other OSes.
This happens in 5.2.7 and the latest master commit (88ba729502).

**Comment by WickedSmoke** [comment]
I'm wondering why the fix in 961edc3 requires writing silence.  In the pa_simple implementation for the Faun library I simply skipped the writes and there was no jump in CPU usage.

My use case is suspending all audio output (pausing a game) so that CPU usage will be zero.   PulseAudio provides pa_stream_cork which will accomplish this, but that requires using the full API rather than pa_simple.

The [Faun backend](https://github.com/WickedSmoke/faun/blob/master/sys_pulseaudio.c) now uses the full API and it's not much larger than the simple one.  Note that this also avoids the overhead of another thread which pa_simple creates.

**Comment by allefant** [comment]
Ah, yes, even better:
```
al_set_voice_playing(al_get_default_voice(), on_off);
```

**Comment by SiegeLord** [comment]
You can't stop a voice that has mixers attached to it.

The reason why I made it feed silence is because that's what all the other backends are doing. I'm not sure why things are designed this way. There is no mechanism by which a voice is informed whether the mixer attached to it is running or stopped.

As it stands now, the intended method to truly stop everything is to detach everything from the voice. So,

`al_detach_mixer(al_get_default_mixer())` to stop and `al_attach_mixer_to_voice(al_get_default_mixer(), al_get_default_voice())` to resume.

**Comment by WickedSmoke** [comment]
Thanks for the info.  Using al_detach_mixer() works without causing the jump in CPU usage, so that's what I'll use.

It would be helpful if the documentation contained that little example of how to pause all audio.  Searching for "suspend" or "pause" turns up nothing about voices or mixers, so maybe it could be put in the al_set_voice_playing section since that function doesn't work as I would expect.
