### ISSUE TITLE
Benchmark lock_more in TTF addon

### ISSUE THREAD

**Issue by trentg** [liballeg/allegro5#493]
Has anyone benchmarked this? Seems potentially to me that this feature actually would slow things down. Is locking several small regions really slower than locking a region that is usually bigger than the combined small regions?

**Comment by fatcerberus** [comment]
I would imagine locking the larger area to be faster--less overhead.

**Comment by trentg** [comment]
I'm not looking for imaginings. I trust my own imaginings vastly more than yours. Looking for benchmarks. :P

**Comment by fatcerberus** [comment]
Woah woah, easy there tiger. :P. I only said "I imagine" because I don't know the exact application of `lock_more`.

So I'll give you something concrete: in minisphere, my game engine, I used to load fonts into an atlas by locking individual regions of the atlas, one lock/unlock per character.  This took forever.  Once I switched to locking the entire atlas once, loading became nearly instantaneous.

Locking bitmaps is EXPENSIVE.  Anything to minimize the number of locks is a performance win.

Someone else should still benchmark this, I don't argue that.  But if it does what I think it does from a quick look at the code, I'm 99% sure taking it out won't help.

**Comment by SiegeLord** [comment]
I tried it a bit just now (I measured the duration of the first call to `render` in `ex_ttf`). Here are the timings:

```
current behavior:

0.024976
0.023902
0.018661
0.018057
0.022727
0.018038
0.020550
0.022419
0.015877
0.027919

mean: 0.021
sem: 0.0011

lock_more = false:

0.021081
0.022587
0.023351
0.017067
0.019143
0.022089
0.017717
0.016917
0.020223
0.017109

mean: 0.020
sem: 0.0008
```

So it seems that not doing lock_more is just a tiny bit faster in this case. That said, I don't know how realistic `ex_ttf` is in terms of usage of the TTF addon...

**Comment by elias-pschernig** [comment]
SHA d3931f14a64a028068113e94d7645f07789b1382 says it is faster (for measuring, not for rendering), and I know Peter did extensive benchmarks back then.

**Comment by trentg** [comment]
I wrote a very simplistic benchmark  that times creating 1000 glyphs, as 0-10 character strings and 1 character strings... with OpenGL there's not much difference, with D3D it appears that the way it is now is faster. So closing this.

**Comment by trentg** [comment]
Could possibly indicate that D3D performance is not optimal, though...

**Comment by trentg** [comment]
Actually D3D locking appears vastly slower than OpenGL which I didn't expect. Might be worth checking for bottlenecks.
