### ISSUE TITLE
android sound keeps playing in background

### ISSUE THREAD

**Issue by elias-pschernig** [liballeg/allegro5#518]
The OpenSL driver on Android keeps playing sound even when the application is switched out, which is a somewhat serious bug. It can be worked around in the application by detecting the switch and then stop playing music and sound, but then it still streams silence. It looks to me that right now exiting an Allegro game which uses sound will always drain the battery within an hour or so, just streaming silence.

**Comment by trentg** [comment]
An hour? Weak battery. But really, it's up to the application to handle this... some may want to keep sound on in the background.

**Comment by elias-pschernig** [comment]
Hm, not sure. Is it the same on iOS? I think we should try and keep Android and iOS in sync, so at least special cases for mobile ports of the game can cover both iOS and Android. I guess "closing" the app on Android is less like the close button and more like the minimize button - so I guess I should pause the mixer manually.

**Comment by trentg** [comment]
Not sure on iOS but I think it stops sound, mainly because Apple forbids you to keep playing sound when minimized. On Android though there are music apps etc that keep playing sound when minimized. For a game, it's usually best to stop the sound, but if I think outside the box, there are probably games that could make a case for not doing so. Myself I don't see why an #ifdef (Allegro already provides the ALLEGRO_IPHONE/ALLEGRO_ANDROID macros) is a big deal, since you have to handle the halt/resume already anyway.

**Comment by SiegeLord** [comment]
Yeah, this is definitely (somewhat) common with Android apps.

**Comment by trentg** [comment]
It's impossible to write a non-trivial game without some platform specifics. For example if you want achievements, you need specifics. And about a million other things, even things not involving another API... we can only bring it so far or we have Java (which we all know isn't Write Once Run Everywhere either.)

**Comment by elias-pschernig** [comment]
Ok, I'm closing this, figured out a way to do it and added a note to the HALT_DRAWING event in the documentation. Exiting my app it would eat 2%-3% of battery a day just sitting in the background streaming silence even after I called al_set_mixer_playing(0) to stop the game music - destroying the voice however works. 2% or 3% doesn't seem a lot, but imagine having 20 games installed on your phone then wonder why the battery capacity is halved :P
