### ISSUE TITLE
Straighten out Windows dynamic dependencies

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#548]
Currently A5 has code to dynamically open the following dlls:

1. DirectSound - `dsound.dll`
2. User32 - `user32.dll`
3. RichEdit - `msftedit.dll` or `riched20.dll` or `riched32.dll`
4. D3DX9 - `d3dx9_${version}.dll`
5. XInput - `xinput1_${version}.dll`

There are a few issues with this. First, despite the code to do that, we nevertheless link the import libraries for DirectSound, User32, XInput and D3DX9, making that code pointless (except in the case of User32, see below). This seems like the easiest point to fix: we should not be linking in those import libraries.

The second issue is whether we even need to do this dynamic lookup. It's definitely a good idea for the last 3 dependencies, as the exact DLL version is unknown. The `user32.dll` code is special as we use it to look up Win7+ symbols. This usage seems completely justified. Not so for DirectSound. We use that library wholesale and it has no variability in DLL name, the sole motivation seems to have been outlined in this thread: https://www.allegro.cc/forums/thread/603813 Namely, it was to reduce the number of libraries you need to specify when statically linking. I think we failed on that front anyway with the other libraries we link to (e.g. opengl32 and others) and it's not even an issue if you use Nuget packages which specify this for you automatically.

So I propose the following:

* Remove the import library linking for XInput and D3DX9 and document that they will be looked up dynamically.
* Remove dynamic linking of DSound, for simplicity

**Comment by fatcerberus** [comment]
Regarding user32 and Win7: Note that with MSVC, unless Allegro itself is compiled with the XP toolchain (Project Properties -> Toolset -> Visual Studio <version> - Windows XP), Win7+ is required anyway due to the stuff from `psapi.h` being moved into kernel32.  If the official Allegro MSVC binaries aren't already compiled with the XP toolchain, that should be updated.

Loading XInput and D3DX9 dynamically makes sense, since these are part of the DirectX redistributable and won't be present on clean Windows installs (Win10 may be an exception, but they definitely aren't present in a clean Win8.1 install).  So yes, that's justified.

Dynamically linking DSound on the other hand serves no purpose, since it's present even in a clean install of WinXP (and possibly even Win2000).

**Comment by SiegeLord** [comment]
We're using the XP toolset (see https://github.com/SiegeLord/allegro_winpkg/blob/master/universal/build_nuget.cmd#L3), so at least that's fine.

**Comment by SiegeLord** [comment]
Hit this when building on Win10. The DLL in question was XInput. Probably something that's important to fix before 5.2...

**Comment by fatcerberus** [comment]
> XInput in particular is rarely distributed on modern Windowses

Is this true?  I don't remember ever having an issue getting minisphere up and running on a clean Win10 install.  Although I suppose it's always possible I'm just automatically updating my DX runtime without thinking about it...

**Comment by SiegeLord** [comment]
Yes, XInput1.3 isn't there in my installation of Win10. See also discussion here: https://www.allegro.cc/forums/thread/615962.
