### ISSUE TITLE
al_draw_line skipping pixels when drawing to bitmap

### ISSUE THREAD

**Issue by koro-xx** [liballeg/allegro5#587]
When drawing to a bitmap, the following function skips at least one horizontal line, and doubles another (result here: http://imgur.com/qIBIyXr )
when drawing on the display directly, or when using a stroke size 2, this doesn't happen.

```
void draw_board(){
    int i;
    al_clear_to_color(al_map_rgb(0,150,250));
    
    for(i=0; i<=20; i++){
        al_draw_line(i*30, 0, i*30, 600, al_map_rgb(0.5,0.5,0.5), 1);
        al_draw_line(0, i*30, 600, i*30, al_map_rgb(0.5,0.5,0.5), 1);
    }
}
```

**Comment by koro-xx** [comment]
I see that this is caused by the integer coordinates (if I add 0.5 to each coordinate then there is no issue). But it seems to me that this should be dealt with somehow by the drawing function so that it has a more consistent behavior, no?

**Comment by fatcerberus** [comment]
This is actually normal and expected behavior for GPU-accelerated rendering, e.g. rectangle functions behave similarly.  If you imagine a piece of graph paper, in traditional raster graphics, coordinates refer to the center of a box (i.e. the pixel itself), whereas in modern graphics libraries they refer instead to intersections in the graph (i.e. between pixels).

**Comment by koro-xx** [comment]
I understand that coordinates refer to the intersections in the graph. What I meant is that the behavior of the drawing routine should be more consistent when the stroke is 1 and the coordinates are integers. Right now what it's doing seems to be pretty random (skipping some lines entirely and doubling others). 
Maybe the drawing routines should behave differently if there's no multisampling?

**Comment by fatcerberus** [comment]
It would be easy enough to change the routine to, say add 0.5 to the coordinates - however, this would break down when, e.g. transformations are in use (say you have a transformation that maps the entire screen to (0,0)-(1,1)).  The inconsistency you see is just a side effect of how pixels are addressed in hardware.  It's the game's job to compensate, not Allegro's.  At least that's my opinion.  I'll leave it up to the other Allegro maintainers to add their two cents. :smiley:

**Comment by fatcerberus** [comment]
Actually now that I think of it transforms are a good way to make this less painful - just apply a transform that translates everything by (0.5, 0.5).  I guess Allegro could do this for you with the default transform - but it wouldn't really be an "identity" matrix then would it? ;)

**Comment by elias-pschernig** [comment]
Transforms are not a good idea at all as they would also transform other things like pictures, rectangles, circles... i.e. things where it would be very very wrong to shift them by 0.5.
This should explain things: http://liballeg.org/a5docs/trunk/primitives.html#pixel-precise-output

**Comment by koro-xx** [comment]
I understand how the coordinates work, and I understand how i can get "pixel coordinates". My issue is with the fact that the drawing depends on whether or not there is multisampling. So if you have a drawing function and you don't know whether or not multisampling is available,  this is very unreliable (it may work perfectly fine sometimes and draw everything wrong in other times).
But if this is OpenGL's fault I suppose that nothing can be done.

**Comment by fatcerberus** [comment]
This is just how GPU rendering works.  You'd get the same outcome if you used OpenGL directly.  I'm not 100% sure about D3D, but I'd expect similar behavior there too.

By giving integral endpoints for a straight line, you're asking the GPU to draw a line between pixels (you know this, of course).  With multisampling, this mostly works because the GPU antialiases everything and thus "sees" the line (however I wouldn't be surprised if the lines got "dimmed" in the process).  Without the multisampling, the GPU only lights pixels which your width-1 line happens to cross (which as you've seen could be one, two, or none).  IMO it's not Allegro's job to second-guess the graphics system.

**Comment by trentg** [comment]
There's always tradeoffs. In this case if we made integral values work as expected, it would be a pain to get the behaviour we have currently. So we do the right thing, which is essentially nothing (except for D3D where we shim in a slight transformation because D3D and OpenGL are different.)

**Comment by koro-xx** [comment]
okay, i'm closing this, thanks for the feedback
