### ISSUE TITLE
Add al_backup_dirty_bitmaps

### ISSUE THREAD

**Issue by goobliata** [liballeg/allegro5#647]
Now it's done in al_flip_display (D3D and Android)... it's a problem because backing up dirty bitmaps
can take a long time (0.5 seconds or more), which can interface with your timers. It's best to stop
your timers, backup dirty bitmaps, then restart them so you don't get timing blips because of backing
up bitmaps.

**Comment by beoran** [comment]
Why exactly is it so slow, and could the work be divided over different
frames?

**Comment by elias-pschernig** [comment]
I completely agree - automatically backing up bitmaps is madness. I would like to just completely remove the ALLEGRO_NO_PRESERVE_TEXTURE flag. If a game needs to backup their bitmaps they should do so themselves. We need to extend the documentation a bit and explain which events exactly will mean that video bitmaps are about to be lost (or have been lost). And then they can call al_backup_dirty_bitmaps (and maybe al_restore_lost_bitmaps)?

**Comment by elias-pschernig** [comment]
@beoran: Allegro will transfer every texture from the GPU into a memory cache, whenever the texture is modified. At the end of each frame. Yes, it's as horrible as it sounds :/

**Comment by fatcerberus** [comment]
@elias-pschernig One problem for documentation is that, with D3D at least, textures can be lost for reasons entirely out of your game's control and which you have no way of predicting (a screen resolution change, for example).  The "best" place to do a backup isn't always obvious, though I do agree 100% that doing it between frames automatically is undesirable.

I was also under the impression that D3D tends to be capricious about this and you can suddenly lose a texture for seemingly no good reason at all.  Which is why Allegro handles it for you automatically right now.  How true this is I'm not sure--I haven't actually coded for DirectX in years.

**Comment by beoran** [comment]
Hmm, that does sound like overkill, yes. On the other hand, with direct
draw loosing textures left and right, there does seem to be a need for the
proposed function. You could probably call it once per second or so. This
could also be done with a per bitmap function, I presume?
On 13 Jul 2016 5:32 pm, "elias-pschernig" <notifications@github.com> wrote:

@beoran <https://github.com/beoran>: Allegro will transfer every texture
from the GPU into a memory cache, whenever the texture is modified. At the
end of each frame. Yes, it's as horrible as it sounds :/

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/liballeg/allegro5/issues/647#issuecomment-232393053>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAEWee9XVydoa5caaRyFD6yXZBfluRjJks5qVQT7gaJpZM4JLhfj>
.

**Comment by fatcerberus** [comment]
Come to think of it, in most cases if there's a texture that changes often enough to be a performance issue, then you probably don't need to preserve its contents anyway.  It's only for static bitmaps where this feature actually comes in handy, so you don't have to reload them from disk all the time.

Maybe we could just make it so that ALLEGRO_NO_PRESERVE_TEXTURE is the default, and automatic backups are opt-in?

**Comment by goobliata** [comment]
I wasn't proposing removing the flag or the functionality. Unfortunately
there's no way to predict when textures will be lost, so al_flip_display
is as good a place as any to check if they're dirty and back them up.
If it were possible to know when they'd be dirtied then we wouldn't have
to do it there. I think though that there could be a display option
(perhaps default) that sets whether or not bitmaps are automatically
backed up,
plus adding the function I mentioned.

**Comment by goobliata** [comment]
I'm not really against removing it, other than backwards compatibility though... in that case I suggest having both al_backup_dirty_bitmap and al_backup_dirty_bitmaps (with an s).

**Comment by fatcerberus** [comment]
Regarding that proposed display flag: We technically already have that: Just use ALLEGRO_NO_PRESERVE_TEXTURE with al_set_new_bitmap_flags().  If we add the backup functions, then we could make that flag the default.

**Comment by SiegeLord** [comment]
I think keeping backwards compatibility is important (i.e. keeping both the auto-backup feature and the default), but adding some manual control to it seems like a great idea.

**Comment by goobliata** [comment]
Do we need another option to say NEVER auto-backup bitmaps? I know we have
the NO_PRESERVE flag but say you want to manually backup bitmaps and restore
them yourself? Will the memory be kept around to do the backups to/from? I'll
need to check that out and if not possibly add another display/bitmap option.

**Comment by goobliata** [comment]
This pull request implements al_backup_dirty_bitmap and al_backup_dirty_bitmaps, used them for Android and Windows. https://github.com/liballeg/allegro5/pull/653
