### ISSUE TITLE
Blend modes for tinted bitmaps

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#768]
`al_draw_tinted_bitmap()` and variants are documented to blend the mask color by multiplication.  Would it be possible to allow changing the masking mode, e.g. doing an additive blend instead?

**Comment by SiegeLord** [comment]
In general, anything is possible with shaders. Adding a color to every bitmap pixel before drawing it is also in principle possible if you're willing to draw to a temporary bitmap first. I don't think it's possible without shaders or 2 stage drawing.

**Comment by fatcerberus** [comment]
Thanks, I figured as much.

I wondered if it was possible with the fixed-function pipeline, but it makes sense that it wouldn't be.  My engine allows switching in custom shaders on the fly, and I don't think it's possible to "stack" shaders, so a shader-based solution isn't practical.

**Comment by beoran** [comment]
If you are willing to use a temporary bitmap, al_set_blender will work
fine. Try to play with the example and read the forum threads linked to the
manual to get some ideas.

https://www.allegro.cc/manual/5/al_set_blender

**Comment by fatcerberus** [comment]
I'll look into that, thanks.  I'm not sure how much of a performance issue it will be (this is for compatibility with the old Sphere game engine which had this as a built-in function, which is why I thought maybe it could be done natively), but since it's only for legacy emulation I might be able to swing something.

I'll close this issue since if the fixed-function graphics pipeline can't do this natively then it's rightly out of Allegro's jurisdiction and fully up to the user to implement.  Thanks guys!

**Comment by goobliata** [comment]
FWIW using a secondary buffer should be fast. Seeing as how most games nowadays use dozens of buffers and drawing steps for each effect. Even if you're targetting old (2010) netbooks a single buffer pass isn't going to add much.

**Comment by beoran** [comment]
If you want to do additive blending with tinted bitmaps, this thread shows
how to do it. It's really easy as long as you remember that Allegro uses
premultiplied alpha. Performance should be fine too.

https://www.allegro.cc/forums/thread/612304

On 9 Jun 2017 09:20, "Trent Gamblin" <notifications@github.com> wrote:

FWIW using a secondary buffer should be fast. Seeing as how most games
nowadays use dozens of buffers and drawing steps for each effect. Even if
you're targetting old (2010) netbooks a single buffer pass isn't going to
add much.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/liballeg/allegro5/issues/768#issuecomment-307315458>,
or mute the thread

**Comment by fatcerberus** [comment]
> If you want to do additive blending with tinted bitmaps

What I want to do specifically is to apply the *tint color* to the bitmap using additive blending while drawing the final image normally (i.e. alpha blend with background), which seems to be the reverse of what that forum thread is asking.  Usually tinting is done by multiplication--which makes sense since it's just using it to color vertices of a textured quad--but I would like to be able to use other tinting methods.

This is easy to accomplish by first drawing to a temporary bitmap, then drawing a rectangle of the desired tint color to it using the desired blend mode--and finally drawing the temp bitmap to the screen.  I was mainly worried about performance, but as @goobliata pointed out GPUs are good at slinging pixels around so it shouldn't be a huge issue.
