### ISSUE TITLE
GetVersionEx Deprecated for windows 

### ISSUE THREAD

**Issue by LazierCode** [liballeg/allegro5#831]
d3d_disp.cpp on d3d_init_display func.
GetVersionEx is deprecated.
Change to:
static bool d3d_init_display()
{
   D3DDISPLAYMODE d3d_dm;
   OSVERSIONINFOEX info = { 0 };
   DWORDLONG dwlConditionMask=0;
   _al_d3d_module = _al_win_safe_load_library(_al_d3d_module_name);
   if (_al_d3d_module == NULL) {
      ALLEGRO_ERROR("Failed to open '%s' library\n", _al_d3d_module_name);
      return false;
   }
   VER_SET_CONDITION(dwlConditionMask,VER_MAJORVERSION,VER_GREATER_EQUAL);
   info.dwOSVersionInfoSize = sizeof(info);
   info.dwMajorVersion = 6;
   is_vista=VerifyVersionInfo(&info,VER_MAJORVERSION,dwlConditionMask);
   .... ....

**Comment by beoran** [comment]
VerifyVersionInfo also has been deprecated in Windows 10:
http://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx#base.getting_the_system_version
Now we're supposed to add a manifest to the exe file and then we'll, I don't quite get what to do next. Since both functions are deprecated, why would this be better than GetVersionEx?

**Comment by fatcerberus** [comment]
Without the manifest, the latest you can detect using the version functions is Win8.  Basically you’re never supposed to use a version check as a proxy for feature detection, you’re expected to test for the features you want directly.

**Comment by beoran** [comment]
Interesting, so how would we do such a feature check here?

**Comment by fatcerberus** [comment]
The code in question:
https://github.com/liballeg/allegro5/blob/master/src/win/d3d_disp.cpp#L619-L637

Based on that it looks like Allegro is checking whether the OS is Vista (or later) to know whether to use D3D9Ex.  However it *also* checks whether it can find a `Direct3DCreate9Ex` symbol in the Direct3D DLL.  The version check therefore seems redundant since we're *already* doing a feature detection.

**Comment by beoran** [comment]
OIC, You just look up the symbol in the DLL.  OK, unless someone knows a good reason why we do the OS version check, then let's just drop it. Then we also don't need VerifyVersionInfo.

**Comment by LazierCode** [comment]
the VerifyVersionInfo function has also been deprecated!
it's OK,MS style.looking for symbol from D3DEx dll is a better idea.
