### ISSUE TITLE
Shutting down and reinitializing Allegro switches to software

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#859]
After shutting down Allegro and reinitializing it including recreating the display, things get really slow, as though Allegro is doing bitmap drawing entirely in software.

This is reproducible on many different machines; there doesn't seem to be a common denominator.  Display mode is OpenGL with programmable pipeline enabled.

Allegro 5.2.3.

**Comment by SiegeLord** [comment]
Err... is this Windows? Tried it on Linux, at it appears to work fine.

**Comment by fatcerberus** [comment]
Most of my testing is Windows, but I remember running into this on Linux too.

**Comment by SiegeLord** [comment]
I'll try it out, I feel like this is something that will be specific to how you're using it. Is it easy to reproduce once I build your engine?

**Comment by fatcerberus** [comment]
Should be, try making a `test.js` file with this code and run it using the engine:
```js
let img = LoadImage('test.png');
while (true) {
    if (Keyboard.Default.isPressed(Key.Space)) {
        Sphere.restart();
    }
    img.blit(0, 0);
    FlipScreen();
}
```

Press F11 to show the framerate counter if it's not visible, then press spacebar to trigger a restart and see if it slows down afterwards.

**Comment by SiegeLord** [comment]
Alright, got it working and was able to reproduce it. The issue here is that Allegro remembers the values of its global settings across re-initializations (in this case, bitmap flags).

In main.c:266 you set the bitmap flags to `ALLEGRO_NO_PREMULTIPLIED_ALPHA` which is logically the same as `ALLEGRO_NO_PREMULTIPLIED_ALPHA | ALLEGRO_VIDEO_BITMAP`. The default flags for Allegro are `ALLEGRO_CONVERT_BITMAP`.

`ALLEGRO_CONVERT_BITMAP` means that if you load the bitmap before the display is created (which minisphere appears to do a lot) it first gets loaded as a memory bitmap and then gets converted to a proper video bitmap once the display is created.

The flags you use makes it load as a memory bitmap and stay that way. There are 3 things to do here:

- Maybe Allegro should reset all of its state upon initialization
- You should set your flags to have `ALLEGRO_CONVERT_BITMAP` in them, as that's likely the best default
- Unrelatedly, but while I'm here, `ALLEGRO_NO_PREMULTIPLIED_ALPHA` is deprecated as a bitmap format. Instead, you should use `al_load_bitmap_flags_f` with that flag instead, so you could avoid all this by just removing that `al_set_new_bitmap_flags` entirely.

**Comment by SiegeLord** [comment]
Closing this in favor of a separate bug that deals with all TSL initialization issues.

**Comment by fatcerberus** [comment]
The bitmap loaded prior to display creation is the window icon.  All other bitmaps are created afterwards.  If what you say is true, how come the first run works normally?

**Comment by SiegeLord** [comment]
You load a whole bunch of bitmaps in `legacy_init`. The problematic bitmaps are in the system font, which is used to draw the FPS counter. I'm guessing is that if you didn't actually draw the FPS, then the FPS would have been fine XD.

**Comment by fatcerberus** [comment]
> Unrelatedly, but while I'm here, ALLEGRO_NO_PREMULTIPLIED_ALPHA is deprecated as a bitmap flag. 

By the way, when did this happen?  For what it's worth, the way I normally look up Allegro APIs is by Googling the function.  Doing that almost invariably gets me the Allegro 5.0 documentation, e.g.:
https://www.allegro.cc/manual/5/al_set_new_bitmap_flags

No idea why Google isn't picking up the latest documentation.

**Comment by fatcerberus** [comment]
> You load a whole bunch of bitmaps in legacy_init. The problematic bitmaps are in the system font, which is used to draw the FPS counter. I'm guessing is that if you didn't actually draw the FPS, then the FPS would have been fine XD.

OH!  Thanks, forgot about that.  I still have no idea why it requires a reinitialization to trigger the issue, though.

**Comment by SiegeLord** [comment]
The deprecation is pretty ancient, I think 5.0.5 by the looks of it. Here's how the issue works again:

1st pass:
1. Font loaded, new bitmap flags are ALLEGRO_CONVERT_BITMAP
2. Display created, font converted to video bitmap
3. New bitmap flags are set to ALLEGRO_NO_PREMULTIPLIED_ALPHA

2nd pass:
1. Font loaded, new bitmap flags are ALLEGRO_NO_PREMULTIPLIED_ALPHA
2. Display created, font remains a memory bitmap

**Comment by fatcerberus** [comment]
Alright, thanks!  Sorry to be a pest, it's just I like to fully understand a bug before trying to fix it.
