### ISSUE TITLE
Checked items in allegro menus remain checked

### ISSUE THREAD

**Issue by RestfulCargo** [liballeg/allegro5#898]
Hello SiegeLord and allegro devs:

Apologies if this has been posted before. As the title says checked items stay checked even if I click on them or try to initialize them with al_set_menu_item_flags. At least visually they remain with a checkmark. I am using allegro version 5.2.4.0 with Visual Studio 2015 (installed through Nuget). Linking with allegro_monolith-static.lib. Behavior can be reproduced with ex_menu.c. I talked to a few people at #allegro irc and they told me in linux this works fine.

Thank you for your time

**Comment by SiegeLord** [comment]
The issue is that https://github.com/liballeg/allegro5/blob/8e55d8348564d499c5cfde5bde138dca51bc2ed9/addons/native_dialog/win_dialog.c#L708 is searching by the wrong id, although searching at all is wrong at that point. Probably need to accomplish this via internal routines.

As a workaround, call al_toggle_menu_item_flags(menu, id, ALLEGRO_MENU_ITEM_CHECKED); when you get the clicked event yourself (but only on Windows).

**Comment by RestfulCargo** [comment]
When I try this suggestion VisualStudio reports al_toggle_menu_item_flags as undefined.

**Comment by SiegeLord** [comment]
Ah yeah, that function's deprecated. You can do `al_set_menu_item_flags(menu, id, al_get_item_flags(menu, id) ^ ALLEGRO_MENU_ITEM_CHECKED)`

**Comment by RestfulCargo** [comment]
That works. Thanks! 
Used to think passing the id as the second parameter was enough but this is fine.

**Comment by SteveFosdick** [comment]
So does https://github.com/liballeg/allegro5/commit/3bab6c6329ab458f351007674d08b2faba5bdc2b#diff-c00d54ada8b12698b4259250bfddd770 fix this?

**Comment by SteveFosdick** [comment]
Why has this been closed?  Surely having to use the API differently from Windows compared to other OSes is not right.  The point of using a cross platform library is specifically to get away from doing things like that.

**Comment by fatcerberus** [comment]
It was closed automatically by the commit that fixed it.
